### ISSUE TITLE
Styling is needed. Projects are needed as well.

### ISSUE THREAD

**Issue by TheDThompsonDev** [xanderyzwich/resume-js#2]
Styling is needed. Projects are needed as well.

**Comment by xanderyzwich** [comment]
This probably won't be closed soon, but thank you for helping me to track this recommendation

**Comment by xanderyzwich** [comment]
Projects are listed generically.  Links should be added.  Personal projects will be given index.html for github pages before links are added.

**Comment by xanderyzwich** [comment]
Project links should be achieved by the catching of any element called "url" that will add a link to the closest header it is contained
